// You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.

// A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.

#include <bits/stdc++.h>
using namespace std;

void solve(string str, vector<string>& ans, string output, int index)
{
	if(index>=str.size())
	{
          if (output.size()) {
            ans.push_back(output);
          }
                return;
	}
	solve(str,ans,output,index+1);
	char x = str[index];
	output.push_back(x);
	solve(str,ans,output,index+1);
}
vector<string> subsequences(string str){
	
	vector<string> ans;
	string output;
	int index = 0;
	solve(str, ans, output, index);
	return ans;	
}
